/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'cart-sessions': CartSession;
    media: Media;
    'shop-categories': ShopCategory;
    'tire-types': TireType;
    'tire-models': TireModel;
    'tire-variants': TireVariant;
    'wheel-types': WheelType;
    'wheel-models': WheelModel;
    'wheel-variants': WheelVariant;
    products: Product;
    requests: Request;
    'tire-iq-articles': TireIqArticle;
    'people-stories': PeopleStory;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'tire-models': {
      variants: 'tire-variants';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'cart-sessions': CartSessionsSelect<false> | CartSessionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'shop-categories': ShopCategoriesSelect<false> | ShopCategoriesSelect<true>;
    'tire-types': TireTypesSelect<false> | TireTypesSelect<true>;
    'tire-models': TireModelsSelect<false> | TireModelsSelect<true>;
    'tire-variants': TireVariantsSelect<false> | TireVariantsSelect<true>;
    'wheel-types': WheelTypesSelect<false> | WheelTypesSelect<true>;
    'wheel-models': WheelModelsSelect<false> | WheelModelsSelect<true>;
    'wheel-variants': WheelVariantsSelect<false> | WheelVariantsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    requests: RequestsSelect<false> | RequestsSelect<true>;
    'tire-iq-articles': TireIqArticlesSelect<false> | TireIqArticlesSelect<true>;
    'people-stories': PeopleStoriesSelect<false> | PeopleStoriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'content_manager' | 'sales_manager' | 'viewer';
  status: 'active' | 'inactive';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cart-sessions".
 */
export interface CartSession {
  id: number;
  tokenHash: string;
  items:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Max file size: 50 MB. Allowed: JPEG, PNG, WebP, MP4, PDF.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  title: string;
  alt: string;
  mediaType: 'image' | 'video' | 'pdf' | 'certificate' | 'drawing' | 'instruction' | 'render' | 'size_table';
  /**
   * Товар магазина, модель шины или модель диска. Используется для пути в S3: bizon/{shop|tires|wheels}/{slug}/…
   */
  relatedProduct?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'tire-models';
        value: number | TireModel;
      } | null)
    | ({
        relationTo: 'wheel-models';
        value: number | WheelModel;
      } | null);
  sortOrder?: number | null;
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * Мета-теги для публичных страниц. Пустые поля заполняются автоматически на фронтенде.
   */
  seo?: {
    seoTitle?: string | null;
    seoDescription?: string | null;
    /**
     * Через запятую
     */
    seoKeywords?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    robotsIndex?: boolean | null;
    robotsFollow?: boolean | null;
  };
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * BIZON Shop — merch и аксессуары. Шины и диски — в каталоге шин/дисков.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  shopCategory: number | ShopCategory;
  shortDescription?: string | null;
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  price?: number | null;
  priceOnRequest?: boolean | null;
  /**
   * Показывается только когда больше текущей цены.
   */
  oldPrice?: number | null;
  available?: boolean | null;
  color?: string | null;
  size?: string | null;
  material?: string | null;
  /**
   * Комбинации цвета, размера и комплектации. Пустые группы не показываются на сайте.
   */
  variants?:
    | {
        sku?: string | null;
        color?: string | null;
        size?: string | null;
        configuration?: string | null;
        price?: number | null;
        priceOnRequest?: boolean | null;
        /**
         * Используется только при реальной скидке.
         */
        oldPrice?: number | null;
        available?: boolean | null;
        images?: (number | Media)[] | null;
        id?: string | null;
      }[]
    | null;
  mainImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  instructions?: (number | Media)[] | null;
  /**
   * Мета-теги для публичных страниц. Пустые поля заполняются автоматически на фронтенде.
   */
  seo?: {
    seoTitle?: string | null;
    seoDescription?: string | null;
    /**
     * Через запятую
     */
    seoKeywords?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    robotsIndex?: boolean | null;
    robotsFollow?: boolean | null;
  };
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-categories".
 */
export interface ShopCategory {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parentCategory?: (number | null) | ShopCategory;
  description?: string | null;
  coverImage?: (number | null) | Media;
  showInMenu?: boolean | null;
  showOnShopHome?: boolean | null;
  sortOrder?: number | null;
  /**
   * Мета-теги для публичных страниц. Пустые поля заполняются автоматически на фронтенде.
   */
  seo?: {
    seoTitle?: string | null;
    seoDescription?: string | null;
    /**
     * Через запятую
     */
    seoKeywords?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    robotsIndex?: boolean | null;
    robotsFollow?: boolean | null;
  };
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Модель шины: карточка для сайта, характеристики и размеры.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tire-models".
 */
export interface TireModel {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Опционально. Если пусто — заполнится из slug при сохранении.
   */
  modelCode?: string | null;
  /**
   * TBR, OTR, Agriculture и т.д. — техническая группа каталога
   */
  tireType: number | TireType;
  /**
   * Контролируемые model-level значения для фильтрации.
   */
  positions?: ('steer' | 'drive' | 'trailer')[] | null;
  /**
   * Канонический справочник из workbook.
   */
  applicationTypes?: ('long-haul' | 'regional' | 'urban' | 'off-road' | 'winter' | 'snow-mud')[] | null;
  /**
   * Публикуются на карточке модели на сайте. Порядок = порядок на сайте.
   */
  features?:
    | {
        key:
          | 'handling'
          | 'safety'
          | 'high-mileage'
          | 'economy'
          | 'wet-grip'
          | 'anti-wear'
          | 'anti-tear'
          | 'short-braking-distance'
          | 'low-noise'
          | 'heavy-load'
          | 'self-cleaning'
          | 'retreadability'
          | 'stone-ejection'
          | 'low-rolling-resistance'
          | 'heat-dissipation'
          | 'cut-resistance'
          | 'puncture-resistance';
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Добавляйте размеры здесь. SKU создаётся автоматически.
   */
  variants?: {
    docs?: (number | TireVariant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  shortDescription?: string | null;
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  mainImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  documents?: (number | Media)[] | null;
  /**
   * Мета-теги для публичных страниц. Пустые поля заполняются автоматически на фронтенде.
   */
  seo?: {
    seoTitle?: string | null;
    seoDescription?: string | null;
    /**
     * Через запятую
     */
    seoKeywords?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    robotsIndex?: boolean | null;
    robotsFollow?: boolean | null;
  };
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Технические группы шин: TBR, OTR и т.д. Определяют разделы каталога /models/{slug}. Не путать с категориями магазина.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tire-types".
 */
export interface TireType {
  id: number;
  /**
   * Например: TBR — грузовые шины
   */
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Текст для страницы списка моделей этого типа
   */
  description?: string | null;
  /**
   * Для карточек на главной и в меню
   */
  shortDescription?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * Используется детерминированным подбором на сайте
   */
  selectionVehicleTypes: ('long-haul-tractor' | 'regional-truck' | 'construction-dumper' | 'quarry-special')[];
  /**
   * Опубликованные условия, для которых предназначено направление
   */
  selectionConditions: ('long-haul' | 'regional' | 'mixed' | 'off-road')[];
  showInMenu?: boolean | null;
  sortOrder?: number | null;
  /**
   * Мета-теги для публичных страниц. Пустые поля заполняются автоматически на фронтенде.
   */
  seo?: {
    seoTitle?: string | null;
    seoDescription?: string | null;
    /**
     * Через запятую
     */
    seoKeywords?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    robotsIndex?: boolean | null;
    robotsFollow?: boolean | null;
  };
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Размеры и технические параметры конкретной модели шины.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tire-variants".
 */
export interface TireVariant {
  id: number;
  tireModel: number | TireModel;
  sku?: string | null;
  /**
   * Заполняется только из подтверждённого коммерческого источника.
   */
  supplierSku?: string | null;
  /**
   * Например, 315/80R22.5 или 12.00R20.
   */
  sizeRaw?: string | null;
  sizeNormalized?: string | null;
  sizeFormat?: ('metric' | 'imperial') | null;
  nominalWidthMm?: number | null;
  imperialWidthIn?: number | null;
  aspectRatioPct?: number | null;
  constructionCode?: 'R' | null;
  rimDiameterIn?: number | null;
  plyRatingPr?: number | null;
  treadDepthMm?: number | null;
  standardRimIn?: number | null;
  pressureSingleKpa?: number | null;
  pressureDualKpa?: number | null;
  maxLoadSingleKg?: number | null;
  maxLoadDualKg?: number | null;
  loadIndexSingle?: number | null;
  loadIndexDual?: number | null;
  speedSymbol?: ('B' | 'F' | 'G' | 'J' | 'K' | 'L' | 'M') | null;
  overallDiameterMm?: number | null;
  sectionWidthMm?: number | null;
  /**
   * Если не заполнено, используется существующий CTA заявки.
   */
  price?: number | null;
  availabilityStatus?: ('available' | 'on_request' | 'unavailable') | null;
  sortOrder?: number | null;
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Дизайн / линейка дисков. Тип (кованые/литые) — через «Тип дисков». Размеры — в «Размеры и параметры».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wheel-models".
 */
export interface WheelModel {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Кованые, литые и т.д. — техническая группа каталога
   */
  wheelType: number | WheelType;
  series?: string | null;
  /**
   * Маркетинговое название дизайна
   */
  designStyle?: string | null;
  /**
   * Например: кованый алюминий
   */
  material?: string | null;
  /**
   * Должен соответствовать типу дисков
   */
  constructionMethod?: ('forged' | 'cast' | 'flow_formed' | 'steel' | 'other') | null;
  fitmentNotes?: string | null;
  shortDescription?: string | null;
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  mainImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  documents?: (number | Media)[] | null;
  /**
   * Мета-теги для публичных страниц. Пустые поля заполняются автоматически на фронтенде.
   */
  seo?: {
    seoTitle?: string | null;
    seoDescription?: string | null;
    /**
     * Через запятую
     */
    seoKeywords?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    robotsIndex?: boolean | null;
    robotsFollow?: boolean | null;
  };
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Технические группы дисков: кованые, литые и т.д. Не путать с категориями магазина (Outdoor, Merch).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wheel-types".
 */
export interface WheelType {
  id: number;
  /**
   * Например: Кованые диски
   */
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Текст для раздела /shop/wheels
   */
  description?: string | null;
  /**
   * Для карточки на странице магазина
   */
  shortDescription?: string | null;
  coverImage?: (number | null) | Media;
  sortOrder?: number | null;
  /**
   * Мета-теги для публичных страниц. Пустые поля заполняются автоматически на фронтенде.
   */
  seo?: {
    seoTitle?: string | null;
    seoDescription?: string | null;
    /**
     * Через запятую
     */
    seoKeywords?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    robotsIndex?: boolean | null;
    robotsFollow?: boolean | null;
  };
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Посадочные параметры и SKU конкретного размера диска.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wheel-variants".
 */
export interface WheelVariant {
  id: number;
  wheelModel: number | WheelModel;
  /**
   * Например: 22.5×8.25 · 10×335 · ET+120
   */
  sizeLabel: string;
  /**
   * Внутренний код для склада и заявок
   */
  sku?: string | null;
  /**
   * Например: 22.5
   */
  diameter?: number | null;
  /**
   * Например: 8.25
   */
  width?: number | null;
  boltHoles?: number | null;
  /**
   * Диаметр окружности, мм — например: 335
   */
  pcd?: string | null;
  /**
   * мм, со знаком
   */
  offsetET?: number | null;
  /**
   * мм
   */
  centerBore?: number | null;
  loadRating?: string | null;
  weight?: number | null;
  color?: string | null;
  finish?: string | null;
  /**
   * Через запятую или с новой строки — например: 11R22.5, 315/80R22.5
   */
  compatibleTireSizes?: string | null;
  available?: boolean | null;
  price?: number | null;
  priceOnRequest?: boolean | null;
  sortOrder?: number | null;
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requests".
 */
export interface Request {
  id: number;
  clientType?: ('individual' | 'company') | null;
  name: string;
  phone?: string | null;
  email?: string | null;
  city?: string | null;
  companyName?: string | null;
  inn?: string | null;
  position?: string | null;
  purchaseVolume?: string | null;
  preferredContact?: ('phone' | 'email' | 'telegram' | 'whatsapp') | null;
  message?: string | null;
  selectionContext?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  items?:
    | {
        catalogItem?:
          | ({
              relationTo: 'tire-models';
              value: number | TireModel;
            } | null)
          | ({
              relationTo: 'wheel-models';
              value: number | WheelModel;
            } | null)
          | ({
              relationTo: 'products';
              value: number | Product;
            } | null);
        catalogVariant?:
          | ({
              relationTo: 'tire-variants';
              value: number | TireVariant;
            } | null)
          | ({
              relationTo: 'wheel-variants';
              value: number | WheelVariant;
            } | null);
        itemType: 'tire' | 'wheel' | 'shopProduct';
        /**
         * Заполняется автоматически при выборе модели / товара
         */
        itemName: string;
        itemSlug?: string | null;
        parentSlug?: string | null;
        variantLabel?: string | null;
        quantity?: number | null;
        url?: string | null;
        notes?: string | null;
        price?: number | null;
        priceOnRequest?: boolean | null;
        id?: string | null;
      }[]
    | null;
  sourcePage?: string | null;
  sourceForm?:
    | (
        | 'contact'
        | 'tire_selection'
        | 'branding'
        | 'supplier'
        | 'warranty'
        | 'wheel_selection'
        | 'product_quick_order'
        | 'cart'
        | 'hero_cta'
        | 'footer_cta'
        | 'custom'
      )
    | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  utmContent?: string | null;
  utmTerm?: string | null;
  status: 'new' | 'in_progress' | 'contacted' | 'qualified' | 'won' | 'lost' | 'closed' | 'spam' | 'archived';
  notificationStatus?:
    | ('pending' | 'telegram_sent' | 'telegram_failed' | 'email_sent' | 'email_failed' | 'partial_failed')
    | null;
  telegramSentAt?: string | null;
  telegramMessageId?: string | null;
  telegramError?: string | null;
  emailSentAt?: string | null;
  emailError?: string | null;
  sourceIpHash?: string | null;
  userAgent?: string | null;
  assignedTo?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Экспертные статьи для раздела /tire-iq.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tire-iq-articles".
 */
export interface TireIqArticle {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Для карточек в списке статей
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (number | null) | Media;
  author?: (number | null) | User;
  /**
   * Мета-теги для публичных страниц. Пустые поля заполняются автоматически на фронтенде.
   */
  seo?: {
    seoTitle?: string | null;
    seoDescription?: string | null;
    /**
     * Через запятую
     */
    seoKeywords?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    robotsIndex?: boolean | null;
    robotsFollow?: boolean | null;
  };
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Кейсы клиентов для раздела /people-stories.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people-stories".
 */
export interface PeopleStory {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  clientName?: string | null;
  industry?: string | null;
  /**
   * Мета-теги для публичных страниц. Пустые поля заполняются автоматически на фронтенде.
   */
  seo?: {
    seoTitle?: string | null;
    seoDescription?: string | null;
    /**
     * Через запятую
     */
    seoKeywords?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    robotsIndex?: boolean | null;
    robotsFollow?: boolean | null;
  };
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'cart-sessions';
        value: number | CartSession;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'shop-categories';
        value: number | ShopCategory;
      } | null)
    | ({
        relationTo: 'tire-types';
        value: number | TireType;
      } | null)
    | ({
        relationTo: 'tire-models';
        value: number | TireModel;
      } | null)
    | ({
        relationTo: 'tire-variants';
        value: number | TireVariant;
      } | null)
    | ({
        relationTo: 'wheel-types';
        value: number | WheelType;
      } | null)
    | ({
        relationTo: 'wheel-models';
        value: number | WheelModel;
      } | null)
    | ({
        relationTo: 'wheel-variants';
        value: number | WheelVariant;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'requests';
        value: number | Request;
      } | null)
    | ({
        relationTo: 'tire-iq-articles';
        value: number | TireIqArticle;
      } | null)
    | ({
        relationTo: 'people-stories';
        value: number | PeopleStory;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cart-sessions_select".
 */
export interface CartSessionsSelect<T extends boolean = true> {
  tokenHash?: T;
  items?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  mediaType?: T;
  relatedProduct?: T;
  sortOrder?: T;
  status?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
        seoKeywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        robotsIndex?: T;
        robotsFollow?: T;
      };
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-categories_select".
 */
export interface ShopCategoriesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  parentCategory?: T;
  description?: T;
  coverImage?: T;
  showInMenu?: T;
  showOnShopHome?: T;
  sortOrder?: T;
  seo?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
        seoKeywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        robotsIndex?: T;
        robotsFollow?: T;
      };
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tire-types_select".
 */
export interface TireTypesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  shortDescription?: T;
  coverImage?: T;
  selectionVehicleTypes?: T;
  selectionConditions?: T;
  showInMenu?: T;
  sortOrder?: T;
  seo?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
        seoKeywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        robotsIndex?: T;
        robotsFollow?: T;
      };
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tire-models_select".
 */
export interface TireModelsSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  modelCode?: T;
  tireType?: T;
  positions?: T;
  applicationTypes?: T;
  features?:
    | T
    | {
        key?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  variants?: T;
  shortDescription?: T;
  fullDescription?: T;
  mainImage?: T;
  gallery?: T;
  documents?: T;
  seo?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
        seoKeywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        robotsIndex?: T;
        robotsFollow?: T;
      };
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tire-variants_select".
 */
export interface TireVariantsSelect<T extends boolean = true> {
  tireModel?: T;
  sku?: T;
  supplierSku?: T;
  sizeRaw?: T;
  sizeNormalized?: T;
  sizeFormat?: T;
  nominalWidthMm?: T;
  imperialWidthIn?: T;
  aspectRatioPct?: T;
  constructionCode?: T;
  rimDiameterIn?: T;
  plyRatingPr?: T;
  treadDepthMm?: T;
  standardRimIn?: T;
  pressureSingleKpa?: T;
  pressureDualKpa?: T;
  maxLoadSingleKg?: T;
  maxLoadDualKg?: T;
  loadIndexSingle?: T;
  loadIndexDual?: T;
  speedSymbol?: T;
  overallDiameterMm?: T;
  sectionWidthMm?: T;
  price?: T;
  availabilityStatus?: T;
  sortOrder?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wheel-types_select".
 */
export interface WheelTypesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  shortDescription?: T;
  coverImage?: T;
  sortOrder?: T;
  seo?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
        seoKeywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        robotsIndex?: T;
        robotsFollow?: T;
      };
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wheel-models_select".
 */
export interface WheelModelsSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  wheelType?: T;
  series?: T;
  designStyle?: T;
  material?: T;
  constructionMethod?: T;
  fitmentNotes?: T;
  shortDescription?: T;
  fullDescription?: T;
  mainImage?: T;
  gallery?: T;
  documents?: T;
  seo?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
        seoKeywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        robotsIndex?: T;
        robotsFollow?: T;
      };
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wheel-variants_select".
 */
export interface WheelVariantsSelect<T extends boolean = true> {
  wheelModel?: T;
  sizeLabel?: T;
  sku?: T;
  diameter?: T;
  width?: T;
  boltHoles?: T;
  pcd?: T;
  offsetET?: T;
  centerBore?: T;
  loadRating?: T;
  weight?: T;
  color?: T;
  finish?: T;
  compatibleTireSizes?: T;
  available?: T;
  price?: T;
  priceOnRequest?: T;
  sortOrder?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  shopCategory?: T;
  shortDescription?: T;
  fullDescription?: T;
  price?: T;
  priceOnRequest?: T;
  oldPrice?: T;
  available?: T;
  color?: T;
  size?: T;
  material?: T;
  variants?:
    | T
    | {
        sku?: T;
        color?: T;
        size?: T;
        configuration?: T;
        price?: T;
        priceOnRequest?: T;
        oldPrice?: T;
        available?: T;
        images?: T;
        id?: T;
      };
  mainImage?: T;
  gallery?: T;
  instructions?: T;
  seo?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
        seoKeywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        robotsIndex?: T;
        robotsFollow?: T;
      };
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requests_select".
 */
export interface RequestsSelect<T extends boolean = true> {
  clientType?: T;
  name?: T;
  phone?: T;
  email?: T;
  city?: T;
  companyName?: T;
  inn?: T;
  position?: T;
  purchaseVolume?: T;
  preferredContact?: T;
  message?: T;
  selectionContext?: T;
  items?:
    | T
    | {
        catalogItem?: T;
        catalogVariant?: T;
        itemType?: T;
        itemName?: T;
        itemSlug?: T;
        parentSlug?: T;
        variantLabel?: T;
        quantity?: T;
        url?: T;
        notes?: T;
        price?: T;
        priceOnRequest?: T;
        id?: T;
      };
  sourcePage?: T;
  sourceForm?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  utmContent?: T;
  utmTerm?: T;
  status?: T;
  notificationStatus?: T;
  telegramSentAt?: T;
  telegramMessageId?: T;
  telegramError?: T;
  emailSentAt?: T;
  emailError?: T;
  sourceIpHash?: T;
  userAgent?: T;
  assignedTo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tire-iq-articles_select".
 */
export interface TireIqArticlesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  author?: T;
  seo?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
        seoKeywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        robotsIndex?: T;
        robotsFollow?: T;
      };
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people-stories_select".
 */
export interface PeopleStoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  gallery?: T;
  clientName?: T;
  industry?: T;
  seo?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
        seoKeywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        robotsIndex?: T;
        robotsFollow?: T;
      };
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}